version: '3.8'

services:
  postgres:
    image: postgres:15-alpine  # Облегченный образ
    container_name: fin-core-postgres
    environment:
      POSTGRES_DB: account
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data  # Сохранение данных между перезапусками
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:  # Том для хранения данных PostgreSQL